[tool.poetry]
name = "my-first-gui"
version = "0.1.0"
description = ""
authors = ["hamza_dahir <hamza.dahir@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
